In [1]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

- Broadcasting

In [4]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [6]:
array1 * array2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

要素の数が合わないとブロードキャスティングできない

In [7]:
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (1,4) (3,3) 

- .argmax():最大値のインデックス番号を返す
- .argmin():最小値のインデックス番号を返す

In [3]:
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)
print(normal_dist_mat.max())
print(normal_dist_mat.argmax())

[[ 1.37222951 -0.31875845 -1.60541042 -0.55241761 -1.67221025]
 [-0.61355773 -1.36697387 -0.58567468 -0.34238529 -0.14850695]
 [-1.48527249  0.03395441 -1.40001618  0.9323477  -0.6609978 ]
 [-0.92852816  0.2170767   0.68500424 -0.18288619  0.52680749]
 [-0.11212116 -0.22862605  2.06760199  0.74878827 -0.01601602]]
2.0676019913738264
22


In [4]:
normal_dist_mat.flatten()[22]

2.0676019913738264

In [5]:
print(np.max(normal_dist_mat))
print(normal_dist_mat.max())

2.0676019913738264
2.0676019913738264


In [2]:
ndarray = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])
np.save('saved_numpy', ndarray)

In [3]:
loaded_numpy = np.load("saved_numpy.npy")
loaded_numpy

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

- rank : 次元数のこと  
ex) (3,3)のrankは2、(3,3,1)のrankは3

In [7]:
# rankの追加
# 3行3列の2次元の行列がさらに大きい1つの行列の中の要素になったイメージ
ndarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(ndarray.shape)
expanded_ndarray = np.expand_dims(ndarray, axis = 0)
print(expanded_ndarray.shape)
print(expanded_ndarray)

(3, 3)
(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
# rankの追加
ndarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(ndarray.shape)
expanded_ndarray = np.expand_dims(ndarray, axis = -1)
print(expanded_ndarray.shape)
print(expanded_ndarray)

(3, 3)
(3, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [11]:
# rankの追加
ndarray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(ndarray.shape)
expanded_ndarray = np.expand_dims(ndarray, axis = 1)
print(expanded_ndarray.shape)
print(expanded_ndarray)

(3, 3)
(3, 1, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [12]:
squeezed_expanded_ndarray = np.squeeze(expanded_ndarray)
squeezed_expanded_ndarray.shape

(3, 3)

In [14]:
flatten_array = ndarray.flatten()
print(flatten_array.shape)
print(flatten_array)

(9,)
[1 2 3 4 5 6 7 8 9]
